runtime: python312

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /(.*)
  static_files: \1
  upload: (.*)
